### ISSUE TITLE
Saving Dashboard to SOLR does not work

### ISSUE THREAD

**Issue by Brainshack** [lucidworks/banana#15]
Hello,

I installed Bana on my Solr install using the .war file. Banana itself works great, but when I try to save the dashboard to the solr instance, it wont work, because it will try to call localhost:8983 which is not the hostname that I setup. I tried changing the host in config.js to no effect. It sill tried calling localhost:8983, but only when i try to save the dashboard (e.g. calling the banana-int collection in an update)

Is there another Config I am missing or is this a bug?

**Comment by ravikmurthy** [comment]
Christian:

The server specified in config.js is used to specify where the banana-int collection  (or user-renamed dashboard collection)  lives. I want to confirm you have edited this config.js file to specify the server you are using. If you are still getting the error:
1.  A possibility is that you need to refresh the app; you may need to clear the browser history because it caches sometime. Please make sure to save the dashboard you built to a file on your desktop first. You can later load from this file and do a Save.
2.  Also, I assume you have the banana-int collection setup.

If you need a quick workaround, you can save the dashboard file to app/dashboards/<filename>.json and access it as https://<hostname>:<portnumber>/banana/#/dashboard/file/guided.json

Regards,
Ravi

**Comment by Brainshack** [comment]
Hello,

all is setup as it should be. The dash boards work as intended and can load the data from my solr instance. The only thing not working is saving them to the solr server (using the save function in the top right corner. Config.js and my dashboard both point towards the right solr instance.

Here is the error I get:

OPTIONS http://localhost:8983/solr/banana-int/update?commit=true net::ERR_CONNECTION_REFUSED angular.js:9499
TypeError: Cannot read property 'docs' of undefined
    at http://jenkins.vkf.isb.de.renzel.net:8080/banana/app/controllers/dashLoader.js:65:42
    at wrappedCallback (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:6995:59)
    at http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:7032:26
    at Object.Scope.$eval (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:8218:28)
    at Object.Scope.$digest (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:8077:25)
    at Object.Scope.$apply (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:8304:24)
    at done (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:9357:20)
    at completeRequest (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:9520:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://jenkins.vkf.isb.de.renzel.net:8080/banana/vendor/angular/angular.js:9490:11) 

http://localhost:8983 is not existing.

**Comment by aadel** [comment]
This should should be resolved in Banana 1.4. Now dashboards are saved / loaded from Solr instance configured in dashboard settings not config.js

**Comment by ghost** [comment]
@aadel I installed latest release version of bananna 1.6.12 but when I try and get "Save failed Dashboard could not be saved to Solr". Pretty annoying.

**Comment by aadel** [comment]
@fcntl my initial thoughts are banana-int collection is not configured properly, Server settings are trying to access a cross-domain instance without configuring CORS or Solr instance might not be up and running.

**Comment by stumpdk** [comment]
This is still an issue.
I experience it with Solr 6.6 and Banana 1.6.0.

The save error happens when trying to save dashboard settings in Solr using the banana-int core.

When the core is created using the command recommended in the readme (``./solr create -c banana-int``), the schema is wrong, as the dashboard-values are saved in a strings field.

If the field is manually changed using the admin interface to a "string" field, and the core is reloaded, the problem is solved (at least it was in my case).

To prevent the error do this:
* Create the banana-int core using ``./solr create -c banana-int``
* Go to the Solr admin interface
* Choose the banana-int core
* Choose "Schema"
* Choose and delete the field "dashboard"
* Create a new field named "dashboard" and choose "string" as datatype
* Reload the banana-int core

Note: This only works for a clean core without data. If there is docs in the core, delete them first.

A more stable way to solve this would probably be to change the way the dashboard is loaded (in [this line](https://github.com/lucidworks/banana/blob/ef3828a171196c3af90943c1d06b007a21197401/src/app/services/dashboard.js#L390)) so that it takes the first element in the dashboard array.

**Comment by dbms** [comment]
After deploying Banana in SOLR, sometimes you can’t save your dashboards in Banana. 
To enable this, you have to create a core that stores these dashboards.
All you need to do is run the following statement which will create a [banana-int] core.

On the terminal :-
${SOLR_HOME}/bin/solr create_core -c banana-int -d ../server/solr-webapp/webapp/banana/resources/banana-int-solr-5.0/conf

Then restart SOLR...

${SOLR_HOME}/bin/solr restart

Enjoy !!
